// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Panlee_UI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Temperature_history;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_Humidity_history;
extern void ui_event_Button_to_screen2(lv_event_t * e);
extern lv_obj_t * ui_Button_to_screen2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_Temperature;
extern lv_obj_t * uic_Temperature_history;
extern lv_obj_t * uic_Humidity;
extern lv_obj_t * uic_Humidity_history;
extern lv_obj_t * uic_Button_to_screen2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

