// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Panlee_UI

#include "../ui.h"

lv_obj_t * uic_Temperature_air_bathroom;
lv_obj_t * uic_Humidity_bathroom;
lv_obj_t * uic_Toilet_heating_LED;
lv_obj_t * uic_Bathroom_heating_LED;
lv_obj_t * uic_decrement_shower;
lv_obj_t * uic_increment_shower;
lv_obj_t * uic_Bathroom_heating_enable;
lv_obj_t * uic_Toilet_heating_enable;
lv_obj_t * uic_Spinbox_toilet;
lv_obj_t * uic_Spinbox_shower;
lv_obj_t * uic_Temperature_toilet;
lv_obj_t * uic_Temperature_bathroom;
lv_obj_t * uic_Button_to_screen1;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Button_to_screen1 = NULL;
lv_obj_t * ui_Temperature_bathroom = NULL;
lv_obj_t * ui_Temperature_toilet = NULL;
lv_obj_t * ui_Spinbox_shower = NULL;
lv_obj_t * ui_Spinbox_toilet = NULL;
lv_obj_t * ui_Toilet_heating_enable = NULL;
lv_obj_t * ui_Bathroom_heating_enable = NULL;
lv_obj_t * ui_increment_shower = NULL;
lv_obj_t * ui_decrement_shower = NULL;
lv_obj_t * ui_increment_shower1 = NULL;
lv_obj_t * ui_decrement_shower1 = NULL;
lv_obj_t * ui_Bathroom_heating_LED = NULL;
lv_obj_t * ui_Toilet_heating_LED = NULL;
lv_obj_t * ui_Humidity_bathroom = NULL;
lv_obj_t * ui_Temperature_air_bathroom = NULL;
// event funtions
void ui_event_Button_to_screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_increment_shower(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox_shower, 1);
    }
}

void ui_event_decrement_shower(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox_shower, -1);
    }
}

void ui_event_increment_shower1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox_toilet, 1);
    }
}

void ui_event_decrement_shower1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox_toilet, -1);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image1, &ui_img_shower_png);
    lv_obj_set_width(ui_Image1, 100);
    lv_obj_set_height(ui_Image1, 100);
    lv_obj_set_x(ui_Image1, -322);
    lv_obj_set_y(ui_Image1, -173);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_765177840);
    lv_obj_set_width(ui_Image2, 100);
    lv_obj_set_height(ui_Image2, 100);
    lv_obj_set_x(ui_Image2, 33);
    lv_obj_set_y(ui_Image2, -173);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_to_screen1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button_to_screen1, 100);
    lv_obj_set_height(ui_Button_to_screen1, 50);
    lv_obj_set_x(ui_Button_to_screen1, -291);
    lv_obj_set_y(ui_Button_to_screen1, 170);
    lv_obj_set_align(ui_Button_to_screen1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_to_screen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_to_screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temperature_bathroom = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Temperature_bathroom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature_bathroom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature_bathroom, -314);
    lv_obj_set_y(ui_Temperature_bathroom, -83);
    lv_obj_set_align(ui_Temperature_bathroom, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Temperature_bathroom, lv_color_hex(0x14FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature_bathroom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature_bathroom, &ui_font_Font36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature_toilet = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Temperature_toilet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature_toilet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature_toilet, 20);
    lv_obj_set_y(ui_Temperature_toilet, -83);
    lv_obj_set_align(ui_Temperature_toilet, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Temperature_toilet, lv_color_hex(0x14FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature_toilet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature_toilet, &ui_font_Font36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox_shower = lv_spinbox_create(ui_Screen2);
    lv_obj_set_width(ui_Spinbox_shower, 70);
    lv_obj_set_height(ui_Spinbox_shower, 50);
    lv_obj_set_x(ui_Spinbox_shower, -272);
    lv_obj_set_y(ui_Spinbox_shower, -13);
    lv_obj_set_align(ui_Spinbox_shower, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox_shower, 2, 2);
    lv_spinbox_set_range(ui_Spinbox_shower, 10, 32);
    lv_spinbox_set_cursor_pos(ui_Spinbox_shower, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox_shower, 25);
    lv_obj_set_style_text_align(ui_Spinbox_shower, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox_shower, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_Spinbox_shower, LV_TEXT_ALIGN_CENTER, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox_shower, &lv_font_montserrat_30, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Spinbox_toilet = lv_spinbox_create(ui_Screen2);
    lv_obj_set_width(ui_Spinbox_toilet, 70);
    lv_obj_set_height(ui_Spinbox_toilet, 50);
    lv_obj_set_x(ui_Spinbox_toilet, 61);
    lv_obj_set_y(ui_Spinbox_toilet, -17);
    lv_obj_set_align(ui_Spinbox_toilet, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox_toilet, 2, 2);
    lv_spinbox_set_range(ui_Spinbox_toilet, 10, 32);
    lv_spinbox_set_cursor_pos(ui_Spinbox_toilet, 1 - 1);
    lv_spinbox_set_value(ui_Spinbox_toilet, 25);
    lv_obj_set_style_text_font(ui_Spinbox_toilet, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_Spinbox_toilet, LV_TEXT_ALIGN_CENTER, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox_toilet, &lv_font_montserrat_30, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Toilet_heating_enable = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Toilet_heating_enable, 50);
    lv_obj_set_height(ui_Toilet_heating_enable, 25);
    lv_obj_set_x(ui_Toilet_heating_enable, -6);
    lv_obj_set_y(ui_Toilet_heating_enable, 79);
    lv_obj_set_align(ui_Toilet_heating_enable, LV_ALIGN_CENTER);

    ui_Bathroom_heating_enable = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Bathroom_heating_enable, 50);
    lv_obj_set_height(ui_Bathroom_heating_enable, 25);
    lv_obj_set_x(ui_Bathroom_heating_enable, -336);
    lv_obj_set_y(ui_Bathroom_heating_enable, 79);
    lv_obj_set_align(ui_Bathroom_heating_enable, LV_ALIGN_CENTER);

    ui_increment_shower = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_increment_shower, 50);
    lv_obj_set_height(ui_increment_shower, 50);
    lv_obj_set_x(ui_increment_shower, -336);
    lv_obj_set_y(ui_increment_shower, -13);
    lv_obj_set_align(ui_increment_shower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_increment_shower, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_increment_shower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_increment_shower, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_decrement_shower = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_decrement_shower, 50);
    lv_obj_set_height(ui_decrement_shower, 50);
    lv_obj_set_x(ui_decrement_shower, -210);
    lv_obj_set_y(ui_decrement_shower, -14);
    lv_obj_set_align(ui_decrement_shower, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_decrement_shower, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_decrement_shower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_increment_shower1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_increment_shower1, 50);
    lv_obj_set_height(ui_increment_shower1, 50);
    lv_obj_set_x(ui_increment_shower1, -6);
    lv_obj_set_y(ui_increment_shower1, -18);
    lv_obj_set_align(ui_increment_shower1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_increment_shower1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_increment_shower1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_decrement_shower1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_decrement_shower1, 50);
    lv_obj_set_height(ui_decrement_shower1, 50);
    lv_obj_set_x(ui_decrement_shower1, 130);
    lv_obj_set_y(ui_decrement_shower1, -18);
    lv_obj_set_align(ui_decrement_shower1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_decrement_shower1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_decrement_shower1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bathroom_heating_LED = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Bathroom_heating_LED, 20);
    lv_obj_set_height(ui_Bathroom_heating_LED, 20);
    lv_obj_set_x(ui_Bathroom_heating_LED, -210);
    lv_obj_set_y(ui_Bathroom_heating_LED, -77);
    lv_obj_set_align(ui_Bathroom_heating_LED, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bathroom_heating_LED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Bathroom_heating_LED, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bathroom_heating_LED, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bathroom_heating_LED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Bathroom_heating_LED, lv_color_hex(0x8A2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Bathroom_heating_LED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Bathroom_heating_LED, lv_color_hex(0xBE2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Bathroom_heating_LED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Toilet_heating_LED = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Toilet_heating_LED, 20);
    lv_obj_set_height(ui_Toilet_heating_LED, 20);
    lv_obj_set_x(ui_Toilet_heating_LED, 130);
    lv_obj_set_y(ui_Toilet_heating_LED, -77);
    lv_obj_set_align(ui_Toilet_heating_LED, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Toilet_heating_LED, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Toilet_heating_LED, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Toilet_heating_LED, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Toilet_heating_LED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Toilet_heating_LED, lv_color_hex(0x8A2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Toilet_heating_LED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Toilet_heating_LED, lv_color_hex(0xBE2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Toilet_heating_LED, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity_bathroom = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Humidity_bathroom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity_bathroom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity_bathroom, -207);
    lv_obj_set_y(ui_Humidity_bathroom, -148);
    lv_obj_set_align(ui_Humidity_bathroom, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Humidity_bathroom, lv_color_hex(0x14FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity_bathroom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity_bathroom, &ui_font_Font36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature_air_bathroom = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Temperature_air_bathroom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature_air_bathroom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature_air_bathroom, -210);
    lv_obj_set_y(ui_Temperature_air_bathroom, -203);
    lv_obj_set_align(ui_Temperature_air_bathroom, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Temperature_air_bathroom, lv_color_hex(0x14FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature_air_bathroom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature_air_bathroom, &ui_font_Font36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button_to_screen1, ui_event_Button_to_screen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_increment_shower, ui_event_increment_shower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_decrement_shower, ui_event_decrement_shower, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_increment_shower1, ui_event_increment_shower1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_decrement_shower1, ui_event_decrement_shower1, LV_EVENT_ALL, NULL);
    uic_Button_to_screen1 = ui_Button_to_screen1;
    uic_Temperature_bathroom = ui_Temperature_bathroom;
    uic_Temperature_toilet = ui_Temperature_toilet;
    uic_Spinbox_shower = ui_Spinbox_shower;
    uic_Spinbox_toilet = ui_Spinbox_toilet;
    uic_Toilet_heating_enable = ui_Toilet_heating_enable;
    uic_Bathroom_heating_enable = ui_Bathroom_heating_enable;
    uic_increment_shower = ui_increment_shower;
    uic_decrement_shower = ui_decrement_shower;
    uic_Bathroom_heating_LED = ui_Bathroom_heating_LED;
    uic_Toilet_heating_LED = ui_Toilet_heating_LED;
    uic_Humidity_bathroom = ui_Humidity_bathroom;
    uic_Temperature_air_bathroom = ui_Temperature_air_bathroom;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    uic_Button_to_screen1 = NULL;
    ui_Button_to_screen1 = NULL;
    uic_Temperature_bathroom = NULL;
    ui_Temperature_bathroom = NULL;
    uic_Temperature_toilet = NULL;
    ui_Temperature_toilet = NULL;
    uic_Spinbox_shower = NULL;
    ui_Spinbox_shower = NULL;
    uic_Spinbox_toilet = NULL;
    ui_Spinbox_toilet = NULL;
    uic_Toilet_heating_enable = NULL;
    ui_Toilet_heating_enable = NULL;
    uic_Bathroom_heating_enable = NULL;
    ui_Bathroom_heating_enable = NULL;
    uic_increment_shower = NULL;
    ui_increment_shower = NULL;
    uic_decrement_shower = NULL;
    ui_decrement_shower = NULL;
    ui_increment_shower1 = NULL;
    ui_decrement_shower1 = NULL;
    uic_Bathroom_heating_LED = NULL;
    ui_Bathroom_heating_LED = NULL;
    uic_Toilet_heating_LED = NULL;
    ui_Toilet_heating_LED = NULL;
    uic_Humidity_bathroom = NULL;
    ui_Humidity_bathroom = NULL;
    uic_Temperature_air_bathroom = NULL;
    ui_Temperature_air_bathroom = NULL;

}
