// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Panlee_UI

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern void ui_event_Button_to_screen1(lv_event_t * e);
extern lv_obj_t * ui_Button_to_screen1;
extern lv_obj_t * ui_Temperature_bathroom;
extern lv_obj_t * ui_Temperature_toilet;
extern lv_obj_t * ui_Spinbox_shower;
extern lv_obj_t * ui_Spinbox_toilet;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch2;
extern void ui_event_increment_shower(lv_event_t * e);
extern lv_obj_t * ui_increment_shower;
extern void ui_event_decrement_shower(lv_event_t * e);
extern lv_obj_t * ui_decrement_shower;
extern void ui_event_increment_shower1(lv_event_t * e);
extern lv_obj_t * ui_increment_shower1;
extern void ui_event_decrement_shower1(lv_event_t * e);
extern lv_obj_t * ui_decrement_shower1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button_to_screen1;
extern lv_obj_t * uic_Temperature_bathroom;
extern lv_obj_t * uic_Temperature_toilet;
extern lv_obj_t * uic_Spinbox_shower;
extern lv_obj_t * uic_Spinbox_toilet;
extern lv_obj_t * uic_increment_shower;
extern lv_obj_t * uic_decrement_shower;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

