// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Panlee_UI

#include "../ui.h"

lv_obj_t * uic_Button_to_screen2;
lv_obj_t * uic_Humidity_history;
lv_obj_t * uic_Humidity;
lv_obj_t * uic_Temperature_history;
lv_obj_t * uic_Temperature;
lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Temperature = NULL;
lv_obj_t * ui_Temperature_history = NULL;
lv_obj_t * ui_Humidity = NULL;
lv_obj_t * ui_Humidity_history = NULL;
lv_obj_t * ui_Button_to_screen2 = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button_to_screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temperature, 115);
    lv_obj_set_height(ui_Temperature, 38);
    lv_obj_set_x(ui_Temperature, -322);
    lv_obj_set_y(ui_Temperature, -144);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Temperature, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Temperature, "24.0 C");
    lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0x14FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temperature, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &ui_font_Font36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature_history = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Temperature_history, 572);
    lv_obj_set_height(ui_Temperature_history, 146);
    lv_obj_set_x(ui_Temperature_history, -46);
    lv_obj_set_y(ui_Temperature_history, -144);
    lv_obj_set_align(ui_Temperature_history, LV_ALIGN_RIGHT_MID);
    lv_chart_set_type(ui_Temperature_history, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Temperature_history, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Temperature_history, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Temperature_history, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_Temperature_history_series_1 = lv_chart_add_series(ui_Temperature_history,
                                                                              lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Temperature_history_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Temperature_history, ui_Temperature_history_series_1,
                             ui_Temperature_history_series_1_array);

    ui_Humidity = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Humidity, 115);
    lv_obj_set_height(ui_Humidity, 40);
    lv_obj_set_x(ui_Humidity, -328);
    lv_obj_set_y(ui_Humidity, 41);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity, "90% ");
    lv_obj_set_style_text_color(ui_Humidity, lv_color_hex(0x14FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Humidity, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &ui_font_Font36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity_history = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Humidity_history, 572);
    lv_obj_set_height(ui_Humidity_history, 146);
    lv_obj_set_x(ui_Humidity_history, -45);
    lv_obj_set_y(ui_Humidity_history, 43);
    lv_obj_set_align(ui_Humidity_history, LV_ALIGN_RIGHT_MID);
    lv_chart_set_type(ui_Humidity_history, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Humidity_history, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Humidity_history, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Humidity_history, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_Humidity_history_series_1 = lv_chart_add_series(ui_Humidity_history, lv_color_hex(0x808080),
                                                                           LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Humidity_history_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Humidity_history, ui_Humidity_history_series_1, ui_Humidity_history_series_1_array);

    ui_Button_to_screen2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button_to_screen2, 100);
    lv_obj_set_height(ui_Button_to_screen2, 50);
    lv_obj_set_x(ui_Button_to_screen2, 304);
    lv_obj_set_y(ui_Button_to_screen2, 175);
    lv_obj_set_align(ui_Button_to_screen2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_to_screen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_to_screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button_to_screen2, ui_event_Button_to_screen2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);
    uic_Screen1 = ui_Screen1;
    uic_Temperature = ui_Temperature;
    uic_Temperature_history = ui_Temperature_history;
    uic_Humidity = ui_Humidity;
    uic_Humidity_history = ui_Humidity_history;
    uic_Button_to_screen2 = ui_Button_to_screen2;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    uic_Temperature = NULL;
    ui_Temperature = NULL;
    uic_Temperature_history = NULL;
    ui_Temperature_history = NULL;
    uic_Humidity = NULL;
    ui_Humidity = NULL;
    uic_Humidity_history = NULL;
    ui_Humidity_history = NULL;
    uic_Button_to_screen2 = NULL;
    ui_Button_to_screen2 = NULL;

}
