"""Convert PNGs to LVGL 8.3 image C files (RGB565 + alpha, 16-bit, no byte swap).

SquareLine Studio exports images in LVGL 9 format into src/images/, which does
not compile with LVGL 8.3 (and is excluded from the build in platformio.ini).
The images the firmware really uses are generated here into src/app_images/.

Usage:  python tools/img2c.py          (needs: pip install pillow)
It also runs automatically before every build (tools/pre_build.py), and only
regenerates outputs that are older than their PNG or this script.
Edit IMAGES below to add or change images. Names must match the ones declared
with LV_IMG_DECLARE in src/ui.h.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SIZE = 100
IMAGES = [  # (source png, C variable name)
    ("src/shower.png", "ui_img_shower_png"),
    ("src/toilet.png", "ui_img_765177840"),
]


def convert(png, name, out, size=SIZE):
    im = Image.open(png).convert("RGBA").resize((size, size), Image.LANCZOS)
    raw = im.tobytes()
    data = bytearray()
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i:i + 4]
        c = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        data += bytes((c & 0xFF, c >> 8, a))
    rows = ["  " + ", ".join("0x%02x" % v for v in data[i:i + 24]) + "," for i in range(0, len(data), 24)]
    up = name.upper()
    out.write_text(f"""// Generated by tools/img2c.py from {png.name} - do not edit.
#include "lvgl.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
    #define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_{up}
    #define LV_ATTRIBUTE_IMG_{up}
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_{up} uint8_t {name}_map[] = {{
{chr(10).join(rows)}
}};

const lv_img_dsc_t {name} = {{
  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
  .header.always_zero = 0,
  .header.reserved = 0,
  .header.w = {size},
  .header.h = {size},
  .data_size = {size} * {size} * LV_IMG_PX_SIZE_ALPHA_BYTE,
  .data = {name}_map,
}};
""", newline="\n")


def main():
    out_dir = ROOT / "src" / "app_images"
    out_dir.mkdir(exist_ok=True)
    for png, name in IMAGES:
        out = out_dir / f"{name}.c"
        deps = [ROOT / png, Path(__file__)]
        if out.exists() and out.stat().st_mtime >= max(d.stat().st_mtime for d in deps):
            continue
        convert(ROOT / png, name, out)
        print("img2c: wrote", out.relative_to(ROOT))


if __name__ == "__main__":
    main()
