// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Panlee_UI

#ifndef _PANLEE_UI_UI_H
#define _PANLEE_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_shower_png);    // assets/shower.png
LV_IMG_DECLARE(ui_img_765177840);    // assets/toilet(1).png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font24);
LV_FONT_DECLARE(ui_font_Font36);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
